name: CI/CD Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client and Hugo
        run: |
          sudo apt update
          sudo apt install openssh-client -y
          wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.tar.gz
          tar -zxvf hugo_0.58.3_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Hugo version
        run: |
          hugo version

      - name: Hugo Build
        run: |
            hugo

      - name: Archive build artifacts
        run: |
          tar -czvf  www.netspective.media_dist.tar.gz public

      - name: Copy build artifacts to the production server
        run: |
           scp -P22 -o StrictHostKeyChecking=no www.netspective.media_dist.tar.gz "${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_SERVER_IP }}:"
           ssh -p22 -o StrictHostKeyChecking=no -t ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_SERVER_IP }} "bash -i update-netspective-media.sh"
